version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: cg_websocket
    volumes:
      - .:/code
    ports:
      - "80:8000"
    env_file:
      - .env
    depends_on:
      - redis

  # redis:
  #   image: "redis:latest"